site_name: DA-AIRFLOW_RETAILROCKET
site_description: Airflow 기반 RetailRocket 분석 파이프라인 문서
site_url: https://geonyul2.github.io/DA-AIRFLOW_RETAILROCKET/
repo_url: https://github.com/GeonYul2/DA-AIRFLOW_RETAILROCKET
edit_uri: ""
docs_dir: docs

theme:
  name: material
  language: ko
  features:
    - navigation.top
    - content.code.copy

nav:
  - Home: index.md
  - Metrics: metrics.md
  - Runbook: runbook.md

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: false
      toc_depth: "2"
  - pymdownx.highlight:
      anchor_linenums: false
  - pymdownx.superfences
  - pymdownx.inlinehilite

extra_css:
  - stylesheets/extra.css
